---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: platform

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-role
  namespace: platform
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: service-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: platform
roleRef:
  kind: ClusterRole
  name: service-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: platform
spec:
  selector:
    matchLabels:
      app: demo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: demo-backend
        image: demo-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: demo-backend
  namespace: platform
spec:
  selector:
    app: demo-backend
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: platform
data:
  application.yaml: |-
    demo.name: NAME